### ISSUE TITLE
注释错位

### ISSUE THREAD

**Issue by ZhengPeng7** [edu2act/course-PySCE#1]
notebook结尾, 集合操作那里, 集合的内建方法中的适用于可变集合的区域的前四个方法.

**Comment by fishtai0** [comment]
具体说明一下

**Comment by ZhengPeng7** [comment]
![2017-06-27 19-17-18](https://user-images.githubusercontent.com/25921713/27585059-231547c6-5b2a-11e7-9bbb-e0b5b2560f73.png)
不好意思, 没说清.
第四章_py_filling.pdf的结尾, 适用于可变集合的操作那儿, 从intersection_update那行开始到symmetric_difference_update, 注释错位了.
