### ISSUE TITLE
请教问题, 关于{}用字典格式化输出的.md

### ISSUE THREAD

**Issue by ZhengPeng7** [edu2act/course-PySCE#4]
> 原文:
> ```python3
> d = dict(n=42, f=7.03, s='string cheese'')
> '{0[n]} {0[f]} {0[s]} {1}'.format(d, 'other')
> ```
**__为什么这里用字典取值时参数不是字符串, 比如: 'n', 'f', 's', 而是n, f, s?__**

请问这为什么也能取出值来?

**Comment by fishtai0** [comment]
> **an expression of the form `'[index]'` does an index lookup using [`__getitem__()`](https://docs.python.org/3.6/reference/datamodel.html#object.__getitem__)**

Check [Format String Syntax](https://docs.python.org/3.6/library/string.html#formatstrings) for details.
